### ISSUE TITLE
Maven?

### ISSUE THREAD

**Issue by ajayinfoworks** [datadudes/salesforce2hadoop#12]
Any plans to put this product on a public Maven repository?

**Comment by DonDebonair** [comment]
We chose not to do that because **salesforce2hadoop** is an application, not a library. Maven Central only makes sense when other applications need to depend on your project, which is not the case here.
Release builds for salesforce2hadoop can be found [on Github](https://github.com/datadudes/salesforce2hadoop/releases) though, which should be good enough.

[wsdl2avro](https://github.com/datadudes/wsdl2avro), the library on which salesforce2hadoop is built, does reside on Maven Central.

Does that answer your question? Do you have any compelling reasons why you think salesforce2hadoop should be on Maven Central after all?

**Comment by ajayinfoworks** [comment]
We want the output files to be in ORC format so, to begin with, we wanted to extend couple of classes & implement that functionality & if it works well in production then contribute code back to this project. Anyway, we can always fork & do it in our branch. Thanks.

**Comment by DonDebonair** [comment]
I would say the best way in this case is indeed to fork it, and eventually contribute back :+1: That would actually be awesome :)
