### ISSUE TITLE
sbt build error

### ISSUE THREAD

**Issue by jvijayakumar** [datadudes/salesforce2hadoop#3]
Hi,
We are getting the below error during sbt assembly. can you please help to fix the issue.

[error](*:assembly) deduplicate: different file contents found in the following
:
[error] C:\Users\vijayakumar.ivy2\cache\org.apache.hadoop\hadoop-yarn-common\ja
rs\hadoop-yarn-common-2.3.0-cdh5.0.0.jar:org/apache/hadoop/yarn/factories/packag
e-info.class
[error] C:\Users\vijayakumar.ivy2\cache\org.apache.hadoop\hadoop-yarn-api\jars\
hadoop-yarn-api-2.3.0-cdh5.0.0.jar:org/apache/hadoop/yarn/factories/package-info
.class

**Comment by mkrcah** [comment]
Hi there, sure, noted, we'll take a look.

**Comment by mkrcah** [comment]
I tried to reproduce this issue on OSX and Ubuntu, but with no luck - compilation works on both platforms. Unfortunately, I have no access to Windows machines at the moment. 

In any case, you don't need to compile the library yourself in order to use it. You can download the compiled binaries [here](https://github.com/datadudes/salesforce2hadoop/releases)
